apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app.kubernetes.io/name: mindscape-info
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080