apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindscape-auth
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindscape-auth
  template:
    metadata:
      labels:
        app: mindscape-auth
    spec:
      containers:
        - name: mindscape-auth
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team1-mindscape-auth:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mindscape-secret
          resources: 
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20          
