apiVersion: v1
kind: Service
metadata:
  name: mindscape-auth
  namespace: app2
spec:
  type: ClusterIP
  selector:
    app: mindscape-auth
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP