apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: '{{ .Env.SMTP_AUTH_USERNAME }}'
      smtp_auth_username: '{{ .Env.SMTP_AUTH_USERNAME }}'
      smtp_auth_password: '{{ .Env.SMTP_AUTH_PASSWORD }}'
      smtp_require_tls: true

    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default-receiver'
      routes:
      - match:
          severity: critical
        receiver: 'critical-receiver'
        continue: true
      - match:
          severity: warning
        receiver: 'warning-receiver'
      - match:
          team: backend
        receiver: 'backend-team'
      - match:
          severity: info
        receiver: 'default-receiver'

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'pod']

    receivers:
    - name: 'default-receiver'
      email_configs:
      - to: '{{ .Env.SMTP_TO }}'
        headers:
          Subject: '[Monitoring] {{ .GroupLabels.alertname }} - {{ .Status | toUpper }}'
        html: |
          <h2>🚨 Alert: {{ .GroupLabels.alertname }}</h2>
          <p><b>Status:</b> {{ .Status | toUpper }}</p>
          <h3>Alerts:</h3>
          {{ range .Alerts }}
          <hr>
          <p><b>Summary:</b> {{ .Annotations.summary }}</p>
          <p><b>Description:</b> {{ .Annotations.description }}</p>
          <p><b>Labels:</b></p>
          <ul>
            {{ range .Labels.SortedPairs }}
            <li><b>{{ .Name }}:</b> {{ .Value }}</li>
            {{ end }}
          </ul>
          {{ if .Annotations.dashboard_url }}
          <p><a href="{{ .Annotations.dashboard_url }}">📊 View Dashboard</a></p>
          {{ end }}
          {{ end }}

    - name: 'critical-receiver'
      email_configs:
      - to: '{{ .Env.SMTP_TO }}'
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'

    - name: 'warning-receiver'
      email_configs:
      - to: '{{ .Env.SMTP_TO }}'
        headers:
          Subject: '🚨 WARNING: {{ .GroupLabels.alertname }}'

    - name: 'backend-team'
      email_configs:
      - to: '{{ .Env.SMTP_TO }}'
        headers:
          Subject: '🚨 BACKEND: {{ .GroupLabels.alertname }}'
