<<<<<<< HEAD
alertmanager:
  enabled: false

server:
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
=======
server:
  persistentVolume:
    enabled: true
    storageClass: ebs-sc
    size: 8Gi

alertmanager:
  persistentVolume:
    enabled: true
    storageClass: ebs-sc
    size: 2Gi
>>>>>>> e3c5ed7128e1648b009eeff98a66980fa4eeed9f
