apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: <ECR_REPOSITORY_URL>/team1-mindscape-auth:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: auth-secret