apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: app
type: Opaque
stringData:
  ENV_SET: argocd

  SPRING_DATASOURCE_URL: jdbc:mysql://team1-mindscape.crawuy6q4fo6.ap-northeast-2.rds.amazonaws.com:3306/webapp?serverTimezone=Asia/Seoul
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root1234

  SPRING_DATA_REDIS_HOST: team1-redis.lrfh10.0001.apn2.cache.amazonaws.com
  SPRING_DATA_REDIS_PORT: "6379"