apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindscape-info
  namespace: app
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: mindscape-info
  template:
    metadata:
      labels:
        app: mindscape-info
    spec:
      containers:
        - name: mindscape-info
          image: 194722398200.dkr.ecr.ap-northeast-2.amazonaws.com/team1-mindscape-info:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: mindscape-secret
          resources: 
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          # readinessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          # livenessProbe:
          #   tcpSocket:
          #     port: 8080
          #   initialDelaySeconds: 15
          #   periodSeconds: 20   