apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mindscape-info
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mindscape-info
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # 앱 배포 초반 spike 방지용
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15