apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: prometheus
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      http_config:
        follow_redirects: true
        enable_http2: true

    route:
      receiver: discord
      group_by: [alertname]
      group_wait: 3s          # 최초 묶음 대기 짧게
      group_interval: 20s     # 같은 그룹의 추가 알림 최소 간격
      repeat_interval: 1m    # 같은 건이 계속 firing이면 재전송 간격

    
    receivers:
    - name: discord
      webhook_configs:
      - url: http://alertmanager-discord.prometheus.svc.cluster.local:9094/
        send_resolved: true
    
