apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-discord-secret
  namespace: prometheus
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgCHmlsDp/inkNHcyfvxDQyRfsJcvoNOxyJDySM5MeINhCfGIKmyEzws+gWVh56U0yqp7cdd/lZLYz/xR7lnaxXsM7EgIUbI4wFCt7IqvF7j2YggfSaxvly6GXkWqvgPz0GZmCmd3tIHSlCgj3vvuwSc0rUIvMqR6XmWElQx5wdQfLhFtq9FBwrBFR9DVDnnMYZ6B3HaCuQFmjNkFDW9KzHzMl5Zwm8GRpI0yH+3FhX4I0t0FM/jMM8uxfdXs6a6EBlkd9Iy9RhfdTq78z+z1c0PfbXnDLW9VwVTl9hgHAMaoRrcc5TEhNPQQdbPbLEOkTO4aarR1Y4ZxtU+GcJY6XJmoGSBk3vdGECt/d/j9q0pjEAIKLjxj3AC6l4mqhChAlZq1mad1uPLRnOumOsDL3dynF2JYeC+zr2b1p/21xqFcS6caAstqida+Z8G8FmbL4LdFe03uYQ6SQpnu+smJovEqsVkvxB6fWVvQjfF2UoMjWHO5Do2xQY94jDGIftxw0qJ/xxbaURGNqhuiIQ3zUrCTHEwa3ltMaUZ/EuX+Mr0IAygbVWJsPgh+vj1T2G0pKqXTubl9ItIxFvXd8cGJ95GcR+L+SCreFIIa+HBZOMbhxbBpJKVUVia56RrLY9rSOJzDSFcK8O85wr94gfO7qehCo5FlqbFxl5/35VRg1wQ+/7DQOQynoijcISwCF8CyxLuT847JKG4xu5KvpgeGjFeAc/vN1Alb/0zVvWXTHrEPAny099rD/2eTqkYf3es+vLAPOsXVJ2tRIhQTxHxInTpkC9Ux6x1nWlnzM30b+rybQ9kLHkR6f963WotZ6+O/UjqNKcw1WlGptvBjTB8mojXwcTcCyXDRPnoQWZy
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-discord-secret
      namespace: prometheus
