apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus
resources:
  - alertmanager-discord.yaml
  - alertmanager-config-secret.yaml
  - prometheusRule.yaml

# 생성 순서: 브릿지/설정 먼저(-1), Helm(0), 룰은 CRD 생긴 뒤(+1)
patches:
- target:
    kind: Secret
    name: alertmanager-prometheus-kube-prometheus-alertmanager
  patch: |
    - op: add
      path: /metadata/annotations
      value: {"argocd.argoproj.io/sync-wave":"-1"}
- target:
    kind: Deployment
    name: alertmanager-discord
  patch: |
    - op: add
      path: /metadata/annotations
      value: {"argocd.argoproj.io/sync-wave":"-1"}
- target:
    kind: Service
    name: alertmanager-discord
  patch: |
    - op: add
      path: /metadata/annotations
      value: {"argocd.argoproj.io/sync-wave":"-1"}
- target:
    kind: PrometheusRule
    name: pod-high-cpu
  patch: |
    - op: add
      path: /metadata/annotations
      value: {"argocd.argoproj.io/sync-wave":"1"}
