name: Seal Secrets and Commit

on:
  workflow_dispatch:
  push:
    branches:
      - dev-sealed

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  seal:
    runs-on: ubuntu-latest
    env:
      NS: app2
      SECRET_NAME: mindscape-secret
      CONTROLLER_NS: kube-system

      # GitHub Secrets에 등록
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect

      SERVER_REDIS_HOST: ${{ secrets.SERVER_REDIS_HOST }}
      SERVER_REDIS_PORT: "6379"
      SERVER_REDIS_TIMEOUT: "2000"
      SPRING_DATA_REDIS_HOST: ${{ secrets.SERVER_REDIS_HOST }}
      SPRING_DATA_REDIS_PORT: "6379"
      SPRING_DATA_REDIS_TIMEOUT: "2000"

      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      JWT_ACCESSTOKEN_EXPIRATIONTIME: "1800000"
      JWT_REFRESHTOKEN_EXPIRATIONTIME: "1209600000"

      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_SCOPE: email,profile
      GOOGLE_REDIRECT_URI: "{baseUrl}/login/oauth2/code/{registrationId}"

      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      SERVICE_API_KAKAOBOOKS: ${{ secrets.SERVICE_API_KAKAOBOOKS }}
      SERVICE_API_LASTFM: ${{ secrets.SERVICE_API_LASTFM }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GEMINI_MODEL_NAME: gemini-2.5-flash-lite-preview-06-17
      SERVER_SECURITY_ENCRYPTKEY: ${{ secrets.SERVER_SECURITY_ENCRYPTKEY }}

      SERVER_FRONTEND_PAGEURL: https://www.aws.thejymes.com
      INFO_APP_URL: https://mindscape.r53-kjh.shop/api/test

      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,prometheus
      MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: read_only
      MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Install kubeseal
        run: |
          curl -LO https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.1/kubeseal-0.26.1-linux-amd64.tar.gz
          tar -xzf kubeseal-0.26.1-linux-amd64.tar.gz
          sudo mv kubeseal /usr/local/bin/
          kubeseal --version

      - name: Build plaintext Secret yaml (in-memory file)
        run: |
          mkdir -p manifest/msa/secrets
          cat > manifest/msa/secrets/secret3.yaml <<EOF
          apiVersion: v1
          kind: Secret
          metadata:
            name: ${SECRET_NAME}
            namespace: ${NS}
          type: Opaque
          stringData:
            SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
            SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
            SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
            SPRING_DATASOURCE_DRIVER_CLASS_NAME: "${SPRING_DATASOURCE_DRIVER_CLASS_NAME}"
            SPRING_JPA_HIBERNATE_DDL_AUTO: "${SPRING_JPA_HIBERNATE_DDL_AUTO}"
            SPRING_JPA_SHOW_SQL: "${SPRING_JPA_SHOW_SQL}"
            SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}"
            SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}"
            SERVER_REDIS_HOST: "${SERVER_REDIS_HOST}"
            SERVER_REDIS_PORT: "${SERVER_REDIS_PORT}"
            SERVER_REDIS_TIMEOUT: "${SERVER_REDIS_TIMEOUT}"
            SPRING_DATA_REDIS_HOST: "${SPRING_DATA_REDIS_HOST}"
            SPRING_DATA_REDIS_PORT: "${SPRING_DATA_REDIS_PORT}"
            SPRING_DATA_REDIS_TIMEOUT: "${SPRING_DATA_REDIS_TIMEOUT}"
            JWT_SECRET: "${JWT_SECRET}"
            JWT_ACCESSTOKEN_EXPIRATIONTIME: "${JWT_ACCESSTOKEN_EXPIRATIONTIME}"
            JWT_REFRESHTOKEN_EXPIRATIONTIME: "${JWT_REFRESHTOKEN_EXPIRATIONTIME}"
            GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
            GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
            GOOGLE_SCOPE: "${GOOGLE_SCOPE}"
            GOOGLE_REDIRECT_URI: "${GOOGLE_REDIRECT_URI}"
            TMDB_API_KEY: "${TMDB_API_KEY}"
            SERVICE_API_KAKAOBOOKS: "${SERVICE_API_KAKAOBOOKS}"
            SERVICE_API_LASTFM: "${SERVICE_API_LASTFM}"
            GEMINI_API_KEY: "${GEMINI_API_KEY}"
            GEMINI_MODEL_NAME: "${GEMINI_MODEL_NAME}"
            SERVER_SECURITY_ENCRYPTKEY: "${SERVER_SECURITY_ENCRYPTKEY}"
            SERVER_FRONTEND_PAGEURL: "${SERVER_FRONTEND_PAGEURL}"
            INFO_APP_URL: "${INFO_APP_URL}"
            MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}"
            MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS: "${MANAGEMENT_ENDPOINT_PROMETHEUS_ACCESS}"
            MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED: "${MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED}"
          EOF

      - name: Seal it (generate sealed-secret.yaml)
        run: |
          kubectl create -f manifest/msa/secrets/secret3.yaml --dry-run=client -o json \
          | kubeseal --controller-namespace ${CONTROLLER_NS} --format yaml \
          > manifest/msa/secrets/sealed-secret3.yaml

      - name: Remove plaintext file (never commit)
        run: rm -f manifest/msa/secrets/secret3.yaml

      - name: Commit sealed secret (PR)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add manifest/msa/secrets/sealed-secret3.yaml
          git commit -m "[fix]: update sealed secret for ${NS}/${SECRET_NAME}" || echo "no changes"
          git push || \
          (git checkout -b chore/sealedsecret-${{ github.run_id }} && git push -u origin chore/sealedsecret-${{ github.run_id }})